name: add to project

on:
  workflow_call:
    inputs:
      org:
        required: true
        type: string
      project-number:
        required: true
        type: string
    secrets:
      PROJECT_RW_TOKEN:
        required: false
      SLACK_BOT_TOKEN:
        required: false
      SLACK_CHANNEL:
        required: false

permissions: {}

jobs:
  add-to-project:
    name: add to project
    permissions:
      repository-projects: write
    runs-on: ubuntu-latest
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
      - name: add to project
        uses: actions/add-to-project@v1.0.2
        with:
          github-token: ${{ secrets.PROJECT_RW_TOKEN }}
          project-url: "https://github.com/orgs/${{inputs.org}}/projects/${{inputs.project-number}}"

      - name: Notify Slack on failure
        if: failure() && env.SLACK_TOKEN != ''
        uses: senzing-factory/build-resources/slack-failure-notification@v4
        with:
          job-status: ${{ job.status }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
