name: Bandit

on:
  workflow_call:
    inputs:
      python-version:
        default: "3.13"
        description: Python version to use for running Bandit
        required: false
        type: string
      targets:
        default: src
        description: Space-separated list of directories to scan
        required: false
        type: string

permissions: {}

jobs:
  bandit:
    name: Bandit
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run Bandit
        env:
          BANDIT_TARGETS: ${{ inputs.targets }}
        run: |
          pip install bandit
          IFS=' ' read -ra targets <<< "$BANDIT_TARGETS"
          bandit -r "${targets[@]}"
