name: build failure slack notification

on:
  workflow_call:
    secrets:
      SLACK_BOT_TOKEN:
        required: true
    inputs:
      job-status:
        required: true
        type: string

permissions: {}

jobs:
  build-failure-slack-notification:
    runs-on: ubuntu-latest

    steps:
      - uses: slackapi/slack-github-action@v2
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        with:
          method: chat.postMessage
          payload: |
            attachments:
              - color: "FF0000"
                fields:
                  - title: "Status"
                    short: true
                    value: "${{ inputs.job-status }}"
                  - title: "Actor"
                    short: true
                    value: "${{ github.actor }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "`REPO:` _*${{ github.repository }}*_ `BRANCH:` _*${{ env.BRANCH_NAME }}*_ workflow ${{ inputs.job-status }} <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
            channel: "devops-community"
            text: "`REPO:` _*${{ github.repository }}*_ `BRANCH:` _*${{ env.BRANCH_NAME }}*_ workflow ${{ inputs.job-status }} <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
          token: ${{ secrets.SLACK_BOT_TOKEN }}
