name: csharp coverage comment

on:
  workflow_call:
    inputs:
      filename:
        default: "coverage.cobertura.xml"
        required: false
        type: string
      thresholds:
        default: "80 90"
        required: false
        type: string

permissions: {}

jobs:
  coverage:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        id: download
        with:
          pattern: ${{ inputs.filename }}

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with:
          badge: true
          fail_below_min: true
          filename: ${{ inputs.filename }}
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: ${{ inputs.thresholds }}

      - name: Add Coverage PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          recreate: true
          path: code-coverage-results.md
