name: 'dependabot automation'

on:
  pull_request:
    branches: [main]

jobs:

  add-pr-to-project:
    if: ${{ github.actor == 'dependabot[bot]' && ( github.event.action  == 'opened' || github.event.action  == 'reopened' ) }}
    uses: senzing-factory/build-resources/.github/workflows/add-to-project.yaml@main
    with:
      classic: false
      org: ${{ vars.SENZING_GITHUB_ACCOUNT_NAME }}
      project-number: ${{ vars.SENZING_PROJECT_FACTORY }}
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}

  dependabot-approve-and-merge:
    permissions:
      contents: write
      pull-requests: write
    uses: senzing-factory/build-resources/.github/workflows/dependabot-approve-and-merge.yaml@main
    secrets:
      SENZING_GITHUB_CODEOWNER_PR_RW_TOKEN: ${{ secrets.SENZING_GITHUB_CODEOWNER_PR_RW_TOKEN }}
