name: go coverage

on:
  workflow_call:
    inputs:
      coverage-config:
        default: "./.testcoverage.yml"
        description: Path to coverage config, relative to the github workspace.
        required: false
        type: string
      profile:
        default: "cover.out"
        description: Path to coverage profile file.
        required: false
        type: string

permissions: {}

jobs:
  go-coverage:
    name: go coverage
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        id: download
        with:
          pattern: cover*
          merge-multiple: true

      - name: check test coverage
        uses: vladopajic/go-test-coverage@a93b868a4cbcbf18dc3781650fad241f0020e609 # v2.18.8
        with:
          config: ${{ inputs.coverage-config }}
          profile: ${{ inputs.profile }}
