name: install test

on: [push]

permissions:
  contents: read

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - name: install Senzing API
        uses: senzing-factory/github-action-install-senzing-api@65-skern
        with:
          packages-to-install: "senzingapi senzingdata-v5"
          senzingapi-version: "3.12.0-24261"