name: install test

on: [push]

permissions:
  contents: read

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - name: install Senzing API
        uses: senzing-factory/github-action-install-senzing-api@65-skern
        with:
          package(s)-to-install: "senzingapi-runtime senzingapi-tools"
          senzingapi-version: "staging-v4"