---

name: 'issue automation'

on:
  issues:
    types:
      - reopened
      - opened

jobs:

  add-issue-to-project:
    uses: senzing-factory/build-resources/.github/workflows/add-to-project.yaml@main
    with:
      project-number: ${{ vars.SENZING_PROJECT_FACTORY }}
      org: ${{ vars.SENZING_GITHUB_ACCOUNT_NAME }}
      classic: false
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}

  add-issue-labels:
    uses: senzing-factory/build-resources/.github/workflows/add-labels-to-issue.yaml@main
    secrets:
      ORG_MEMBERSHIP_TOKEN: ${{ secrets.ORG_MEMBERSHIP_TOKEN }}
      SENZING_MEMBERS: ${{ secrets.SENZING_MEMBERS }}
