name: lint workflows

on:
  workflow_call:
    inputs:
      default-branch:
        default: main
        description: "Default branch of the repository"
        required: false
        type: string
      validate-all-codebase:
        default: false
        description: "Lint all files or only modified: true/false."
        required: false
        type: boolean
    outputs:
      job-status:
        description: "job status"
        value: ${{ jobs.changes.outputs.job-status && jobs.lint-workflows.outputs.job-status }}

permissions: {}

jobs:
  # In order to require linting as a status check we need to
  # run the overall workflow on every pr.
  # This is used to skip at the job level if there are no
  # changes to the workflow files.
  changes:
    runs-on: ubuntu-latest
    outputs:
      job-status: ${{ job.status }}
      workflows: ${{ steps.changes.outputs.workflows }}
    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            workflows:
              - '.github/workflows/**'

  lint-workflows:
    if: ${{ needs.changes.outputs.workflows == 'true' }}
    name: lint workflows
    needs: changes
    outputs:
      job-status: ${{ job.status }}
    permissions:
      contents: read
      packages: read
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: lint code base
        uses: super-linter/super-linter@v8.2.0
        env:
          DEFAULT_BRANCH: ${{ inputs.default-branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*github/.*
          FIX_BIOME_FORMAT: false
          FIX_BIOME_LINT: false
          # only lint new and modified files
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate-all-codebase }}
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_SHELL_SHFMT: false
