name: 'move pr to project column'

on:
  workflow_call:
    inputs:
      column:
        required: true
        type: string
      project:
        default: "Garage"
        required: false
        type: string
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN:
        required: true

jobs:
  move-pr-to-project-column:
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to project column
        uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          column: ${{ inputs.column }}
          project: ${{ inputs.project }}
          repo-token: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
