name: move pr to done dependabot

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions: {}

jobs:
  move-pr-to-done-dependabot:
    permissions:
      repository-projects: write
    secrets:
      APP_CLIENT_ID: ${{ secrets.SENZING_GITHUB_PROJECT_APP_CLIENT_ID }}
      APP_PRIVATE_KEY: ${{ secrets.SENZING_GITHUB_PROJECT_APP_PRIVATE_KEY }}
    uses: senzing-factory/build-resources/.github/workflows/move-pr-to-done-dependabot.yaml@v4
    with:
      project: ${{ vars.SENZING_PROJECT_FACTORY }}
