name: python coverage comment

on:
  workflow_call:
    outputs:
      job-status:
        description: "job status"
        value: ${{ jobs.coverage.outputs.job-status }}

permissions: {}

jobs:
  coverage:
    outputs:
      job-status: ${{ job.status }}
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v6
        id: download
        with:
          path: coverage-reports
          pattern: coverage-*
          merge-multiple: true

      - name: Combine coverage reports
        run: |
          pipx run coverage combine coverage-reports/*coverage.*

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v5
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
